### ISSUE TITLE
Explain the Placeholders

### ISSUE THREAD

**Issue by lollilol** [PlaceholderAPI/Server-Expansion#11]
Make a wiki page or md file that explains all the placeholders.

this is unclear for me:
whats the difference between %server_total_living_entities% and %server_total_entities%?
whats the difference between %server_ram_total% and %server_ram_max%?
what is %server_total_chunks%

**Comment by aBooDyy** [comment]
Hello there,
We are working on improving the wikis. Sorry about that.

Here's an explanation about the placeholders you asked about:
`%server_total_living_entities%` - Returns the total living entities (such as monsters, players, etc).
`%server_total_entities%` - Returns the total of **all** entities, including living entities (e.g. an item on the ground would be counted in this placeholder).

`%server_total_chunks%` - Returns all loaded chunks on the server.

`%server_ram_total%` - Returns the total amount of memory currently available. 
`%server_ram_max%` - Returns the maximum amount of memory that the virtual machine (the server) will attempt to use.
