### ISSUE TITLE
PlaceHolder Error server_countdown

### ISSUE THREAD

**Issue by Ismael-GT** [PlaceholderAPI/Server-Expansion#12]
Hi, I need to see the cooldown everyday at 09:00

%server_countdown_HH:mm_09:00%

No works! I have tested it a lot, is necessary fix it in the code

**Comment by darbyjack** [comment]
Should be fixed via https://github.com/PlaceholderAPI/Server-Expansion/commit/5bb45758c1f4df08733a64f05c865d30b48809ec. Please re-open if you continue to experience problems.
