### ISSUE TITLE
[Feature] Whitespace

### ISSUE THREAD

**Issue by rErEaT** [PlaceholderAPI/Server-Expansion#13]
Hi!

I am using %server_date_HH:mm:ss% variable from placeholderapi.
This variable will say 11:15:32 but always with difference lenght what cames from font?!

Is it able to set to {server_date_HH:mm:ss+} for being the same length?
Or i have to report this to PlaceholderAPI? :(
Would be nice if you can implement a {whitespaces} variable what works everywhere

**Comment by aBooDyy** [comment]
Hello there,

Can you please explain more about what you want, and what you're getting?
You can use spaces in the SimpleDateFormat argument if that's what you want. So e.g. `%server_time_dd/MM/yyyy HH:mm:ss%`.

Use the correct template when you open an issue and open it in the correct repository next time, please.

Thanks for reaching out,
aBooDyy

**Comment by rErEaT** [comment]
![1](https://user-images.githubusercontent.com/2604798/82799562-869f3180-9e7a-11ea-93c8-2f02921a7ab9.png)
I  mean this, can u see the differences?

for example 11:26:05 and 11:26:11 different lenght

**Comment by Andre601** [comment]
That is caused by the font you use, which isn't the default Minecraft font.
It really isn't something a plugin could change as it would need to know what resource pack you're using to then manipulate the text in a way to make it work well enough.

**Comment by rErEaT** [comment]
Its default minecraft resource pack just with unicast font true in languages. :|

**Comment by Andre601** [comment]
The issue remains: The plugin/expansion would need to know if the player has that option enabled, which it can't know.
So there is no fix for this.
You'll face such an issue with pretty much any font that isn't monospaced.

Also, for clarification. Unicast is not an option. Only "Force Unicode",

"Force Unicode: OFF"
![image](https://user-images.githubusercontent.com/11576465/82800397-ee09b100-9e7b-11ea-9499-d97e0aa5ca70.png)

"Force Unicode: ON"
![image](https://user-images.githubusercontent.com/11576465/82800419-f95cdc80-9e7b-11ea-91a6-9080f6df0df6.png)

You can already tell by the pictures that the unicode one is smaller and different than the normal one.

**Comment by rErEaT** [comment]
yes it's true :/
thanks but i hoped we can create a "block" to reperesent this clock then after that text will be start at the same startpoint.

I know the clock will be difference lenght but can after text start at the same?

**Comment by Andre601** [comment]
I mentioned it twice and it's sad that I have to mention it a third time, but here we go.

You can't have the text on the same line, because not everyone has "Force Unicode Font" set to ON and therefore will have a different font than you have. And the expansion can't just see what font you use and therefore can't pad the output accordingly.
It could only have one specific amount of spaces and that's it.

**Comment by rErEaT** [comment]
Okay, i understand.
