### ISSUE TITLE
%server_uptime% format bug?

### ISSUE THREAD

**Issue by DaeHyeoNi** [PlaceholderAPI/Server-Expansion#16]
![image](https://user-images.githubusercontent.com/1341628/89902520-81ec4d00-dc21-11ea-99b2-40f048f2ed75.png)

It looks like the picture above.
I think it should be the next form.
1d 2h 58m 22s

I don't know why it shows like this. 26h?

**Comment by Fefo6644** [comment]
What's your PAPI version?

**Comment by DaeHyeoNi** [comment]
my papi version is 2.10.9

**Comment by Fefo6644** [comment]
Try updating to the latest dev build: https://ci.extendedclip.com/job/PlaceholderAPI/

**Comment by DaeHyeoNi** [comment]
We've taken action, but we won't know until 24 hours later.

**Comment by DaeHyeoNi** [comment]
fixed in develop branch
