### ISSUE TITLE
Placeholder: %server_uptime% is broken after 2 days

### ISSUE THREAD

**Issue by HexedHero** [PlaceholderAPI/Server-Expansion#17]
The photo explains it https://i.imgur.com/VvLgCNb.jpg
Version is 2.3.1

**Comment by EmeraldSnorlax** [comment]
Adding onto this; the issue still seems to persist beyond 4 days, see the attatched screenshot
![2020-10-22_16 00 41](https://user-images.githubusercontent.com/43452521/96890755-dd3b8680-147f-11eb-8b58-9ef6dd126ceb.png)

**Comment by HexedHero** [comment]
It's fixed by PR https://github.com/PlaceholderAPI/Server-Expansion/pull/21 if it gets pulled. DM me if you want the fixed jar/expansion

**Comment by EmeraldSnorlax** [comment]
Thank you, I'll compile your fork

**Comment by darbyjack** [comment]
Should be fixed via https://github.com/PlaceholderAPI/Server-Expansion/commit/5bb45758c1f4df08733a64f05c865d30b48809ec. Please re-open if you continue to experience problems.
