### ISSUE TITLE
Server countdown functionality improvement

### ISSUE THREAD

**Issue by LogGits** [PlaceholderAPI/Server-Expansion#18]
I wanted to do something that shows time until the next time:
`%server_countdown_HH_17%` (currently shows `0`)
which is 5pm whereby it should show a countdown to the current 5pm.

Use-case; a restart hologram which shows the time until the next restart (5pm).

**Comment by BlitzGamer-88** [comment]
You can use some javascript and the server time placeoholder to calculate the next day and make the count down go until next day. If you don't specify the day, the countdown will count until the current day 17:00.

This can be closed.
