### ISSUE TITLE
%server_time% not working during start.

### ISSUE THREAD

**Issue by Wolfie713** [PlaceholderAPI/Server-Expansion#24]
### Issue
Using DiscordSrv, when the MC server boots up and DiscordSrv reports it in the proper channel, the `%server_time%` value isn't converted to show the time.

### Expected behaviour
Convert the `%server_time%` reference to the current time.

### Actual behaviour
Just show `%server_time%` as is.  (The same string works just fine when stopping, just not when starting.)

Format of string: `%server_time_yyyy-MM-dd@HH.mm.ss zzz%`

### How to reproduce
Reboot the MC server.

### `/papi dump` output

https://paste.helpch.at/cukapuxiki

**Comment by Andre601** [comment]
From my checks in the code is there not even a `time` option anymore/at all?

The only thing I could find are `uptime` and `time_<simpleDateFormat>`
This is also confirmed by the [actual placeholder list](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#server) on the wiki.

So `%server_time%` either is a DiscordSRV internal placeholder, making it a problem of that specific plugin, or you somehow use an older version of the Server expansion, which the Dump you provided denies (Although the version of this repo is currently 2.5.0 but probably wasn't released yet).

**Comment by Wolfie713** [comment]
I'm using the <simpleDateFormat> and it works when stopping, but the exact same format fails when starting.  DiscordSrv has confirmed that all it's doing it calling on the API and not doing anything else with it, ie, it's not on their end.  So it's either PAPI failing to do something before calling the expansion, or it's the expansion itself.

**Comment by Andre601** [comment]
Can you ask them *when* they are calling the method?
It can be that DiscordSRV is trying to parce placeholders with PAPI while PAPI hasn't loaded expansions yet. Expansions are loaded in 2 places:

- When the expansion is part of a plugin and the plugin calls the `register()` method of the expansion.
- When the Server has finished loading. This is usually the case for all external expansions.

It could be the case that DiscordSRV triggers the method before PAPI was able to load the expansions. It would be beneficial if the DiscordSRV devs could share a link to where and when the setPlaceholder is called.

Additionally, is PAPI receiving new events for devs to use, which indicate when either a specific expansion or all expansions have been loaded, but there is no ETA on when this will be published.

**Comment by Scarsz** [comment]
> It could be the case that DiscordSRV triggers the method before PAPI was able to load the expansions. It would be beneficial if the DiscordSRV devs could share a link to where and when the setPlaceholder is called.

DiscordSRV queries the placeholders in an async thread after DiscordSRV loads. DiscordSRV soft-depends on PlaceholderAPI, thus PAPI is finished loading before DiscordSRV queries it. I tested with @Wolfie713 as well with making the message get executed on the main thread during a game tick and it still didn't work. I had to delay the message by 20 ticks to get it working. It definitely seems like you're right that it's a concurrency issue.

> Additionally, is PAPI receiving new events for devs to use, which indicate when either a specific expansion or all expansions have been loaded, but there is no ETA on when this will be published.

Would be beneficial but really it would be much better if PAPI was _actually_ finished loading expansions when the plugin finishes loading

**Comment by Andre601** [comment]
> Would be beneficial but really it would be much better if PAPI was actually finished loading expansions when the plugin finishes loading

Not quite doable.
The way PAPI currently loads expansions was mentioned above. The expansion either gets loaded by a plugin (i.e. is part of the plugin and then registered using `PlaceholderExpansion#register()`. I think DiscordSRV does that now, no?), when the `ServerLoadEvent` is fired or, if that event isn't available (Server is old) after a short delay which from what I saw is apparently 1 tick(?)

The reason why we use to load on the ServerLoadEvent is expansion issues, where PAPI loads the expansion while the server didn't had all resources available, or something similar.

**Comment by Andre601** [comment]
I quickly looked at the history and the issue seems to have been plugins registering AFTER PAPI has loaded their respective expansions, therefore those expansions fail to load or properly hooking into the plugin (Was the case with plugins like vault).

See [PlaceholderAPI/PlaceholderAPI#103](https://github.com/PlaceholderAPI/PlaceholderAPI/issues/103) for complete context

**Comment by Scarsz** [comment]
Delaying the startup message by a while is probably the easiest solution to this entire situation in the standpoint of DiscordSRV then 🤷🏻‍♂️

**Comment by Starmism** [comment]
[PlaceholderAPI/PlaceholderAPI#103](PlaceholderAPI/PlaceholderAPI#103) fixes this issue.
