### ISSUE TITLE
Feature request: %server_build% or similar

### ISSUE THREAD

**Issue by SlimeDog** [PlaceholderAPI/Server-Expansion#29]
`%server_version%` is very useful. Spigot and Paper both include the build number in the `/version` result. Alternatives:
- combined: `%server_version_build%
  - "1.17-3161" (Spigot)
  - "1.17-46" (Paper)
- separate: `%server_build%`
  - "3161" (Spigot)
  - "46" (Paper)

**Comment by SlimeDog** [comment]
I built if for myself, but it would be nice if someone would release it officially.

**Comment by SlimeDog** [comment]
I built it myself, to test.
`papi parse x %server_build%` returns `6c1c1b2` rather than `3246` (the current build number). Please revisit this issue.

**Comment by SlimeDog** [comment]
BTW, I built it initially with Java 11. It failed miserably. I reverted to Java 8, and it works just fine. I assume that was expected.

**Comment by iGabyTM** [comment]
> I built it myself, to test. `papi parse x %server_build%` returns `6c1c1b2` rather than `3246` (the current Spigot 1.17.1 build number).
> 
> > version
> > [18:03:55] [Server thread/INFO]: This server is running CraftBukkit version 3246-Spigot-6c1c1b2-dc764e7 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
> 
> It does return the current build number `295` on Paper 1.17.1.
> 
> > version
> > [18:02:53 INFO]: This server is running Paper version git-Paper-295 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f905057)
> > You are running the latest version
> 
> Please revisit this issue.

why is the format different O.o smh

**Comment by iGabyTM** [comment]
Try this jar @SlimeDog https://cdn.discordapp.com/attachments/548801214557716490/893825459165466654/PAPI-Expansion-Server.jar

**Comment by SlimeDog** [comment]
Thanks for fast response. With that [JAR](https://cdn.discordapp.com/attachments/548801214557716490/893825459165466654/PAPI-Expansion-Server.jar)

Spigot 1.17.1 looks good
>papi parse rambeau %server_version%
[07:36:59] [Server thread/INFO]: 1.17.1
>papi parse rambeau %server_build%
[07:36:53] [Server thread/INFO]: 3246
>papi parse rambeau %server_version_build%
[07:36:44] [Server thread/INFO]: 1.17.1-3246

Paper 1.171 is now not so good -- extra string `(MC: 1.17.1)` after `build`
> papi parse rambeau %server_version%
[07:40:38 INFO]: 1.17.1
> papi parse rambeau %server_build%
[07:40:42 INFO]: 295 (MC: 1.17.1)
> papi parse rambeau %server_version_build%
[07:40:46 INFO]: 1.17.1-295 (MC: 1.17.1)

**Comment by SlimeDog** [comment]
Note that the Spigot build number was added to the version string sometime in the tenure of 1.16.5. Prior to that time, the actual build number was not available. In those cases, I suppose the (for example) `6c1c1b2` bit is the next best thing.

**Comment by SlimeDog** [comment]
Could someone please finish this work -- see the two previous comments -- and publish an official release? Thanks in advance.

**Comment by SlimeDog** [comment]
> Something I wonder: Wouldn't it sound better to have `%server_version_full%` rather than `%server_version_build%`?
> I feel like it makes a bit more sense here since we can see the MC version and build version as full version string I would say...

`%server_version_full%` makes sense to me, better than `%server_version_build%`. Trust is, I don't care about the placeholder names. I do care that they return standard results, which the PR currently does not. A little more string parsing would go a long way.

**Comment by SlimeDog** [comment]
Now if someone will accept the PR ...

**Comment by Andre601** [comment]
Well... I could probs merge it myself, but I want to wait for Gaby's response on it.

**Comment by SlimeDog** [comment]
Someone please build and release officially.

**Comment by SlimeDog** [comment]
Someone please build and release this officially.
