### ISSUE TITLE
[SUGGESTION] A way to disable the `*` when TPS higher than 20

### ISSUE THREAD

**Issue by srnyx** [PlaceholderAPI/Server-Expansion#39]
I have no idea what it means and having it randomly popping up looks weird

**Comment by Andre601** [comment]
`*` means the TPS is above 20 somehow.
This is basically a copy of what Spigot gives in their `/tps` command, so you could ask them about why that is a thing.

**Comment by srnyx** [comment]
> `*` means the TPS is above 20 somehow. This is basically a copy of what Spigot gives in their `/tps` command, so you could ask them about why that is a thing.

Ahhh, okay, weird. I've created a fork by the way for anyone that doesn't want it: https://github.com/srnyx/Server-Expansion
I still think it'd be beneficial to have a config option in this repository (the base/head) for all users.
