### ISSUE TITLE
%server_name% get unreal

### ISSUE THREAD

**Issue by MCJiaoLong** [PlaceholderAPI/Server-Expansion#42]
In Chinese:
我在server.properties改了motd,但是此变量还是显示A Minecraft Server
以及在跨服端(Waterfall)的config改了依旧不是真实的名字
所以请获取motd里的名字而不是直接显示A Minecraft Server
In English(Use translator):
I'm on the server.properties is changed to MOTD, but this variable still shows A Minecraft Server
and the config Waterfall is changed. But it's still not the real name, 
so please obtain the name in MOTD instead of directly displaying A Minecraft Server

**Comment by Andre601** [comment]
The expansion obtains the server name from the PlaceholderAPI config, since the server does no longer have an actual server name.
That property has been removed a while ago.

If you want to use server MOTD, use `%server_motd%` which should be available.
