### ISSUE TITLE
NoClassDefFoundException when loading expansion

### ISSUE THREAD

**Issue by konsheng** [PlaceholderAPI/Server-Expansion#44]
https://pastebin.com/kuNNVGef

**Comment by Andre601** [comment]
Could you please provide actual information, such as steps you did to get this AND a `/papi dump` output?
Just pasting the error doesn't help at all.

**Comment by konsheng** [comment]
https://paste.helpch.at/alulohezex
@Andre601

**Comment by konsheng** [comment]
Do I need to provide any more information?
