### ISSUE TITLE
countdown placeholder won't work using hours.

### ISSUE THREAD

**Issue by matipoirierg** [PlaceholderAPI/Server-Expansion#48]
I'm trying to make a countdown for a certain hour, but the plugin keeps returning 0.
Placeholder used: %server_countdown_HH.mm_16.00%
The placeholder should return a countdown showing the time left for 16:00 and reset after that time is reached.

**Comment by Andre601** [comment]
I'm not an expert, but I think Java's [SimpleDateFormat](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/text/SimpleDateFormat.html) (which is used for the `HH.mm` pattern) doesn't support just providing the hour and minute without any real date.

It's just a guess, but I assume that Java doesn't know what date to use, so it perhaps default to a very low value (Perhaps start of the epoch timestamp?).

What the expansion does is essentially take the provided date (in your case 16.00), convert it to a timestamp and then substract the current time as timestamp from it.

So, if my guess is right and Java defaults to a very old date, would the result be negative, which defaults to 0.

But again, this is just me guessing here.

**Comment by Andre601** [comment]
I've looked into it a bit more closely and my guess got confirmed.
The Date instance returned by the `parse(String)` method (Now [`parse(String, ParsePosition)`](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/text/SimpleDateFormat.html#parse(java.lang.String,java.text.ParsePosition)) it seems?) defaults to specific values if a specific part for the date (i.e. year) is missing.

Quote:
> All of the calendar's date-time fields are [cleared](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/Calendar.html#clear()) before parsing, and the calendar's default values of the date-time fields are used for any missing date-time information. For example, the year value of the parsed Date is 1970 with [GregorianCalendar](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/GregorianCalendar.html) if no year value is given from the parsing operation.

This means, that in your case is the generated date defaulting to the first day of the Gregorian Calendar which for Java is 1st of January 1970, so the final date is less than the current one, meaning it is negative which defaults to 0.

**Comment by matipoirierg** [comment]
I see, thank you very much for your explanation, I ended up using %server_countdown_dd/yyyy/HH:mm_{server_time_dd}/{server_time_yyyy}/16:30% and it's working fine.
