### ISSUE TITLE
Countdown to exact hour and minute every day without need to change it every day.

### ISSUE THREAD

**Issue by SebastianLivoni** [PlaceholderAPI/Server-Expansion#5]
make it possible with adding a placeholder there, so u can set %server_time% placeholder to return the current day and then use it inside the countdown placeholder.

To make it possible to countdown to for example 20:00 every night with placeholderapi countdown?
%servercountdown<SimpleDateFormat>_<time>%

**Comment by aBo0oDyy** [comment]
Hey there,
Thanks for suggesting that, its now possible with the new version [2.2.2](https://api.extendedclip.com/expansions/server/versions/server-222/) to add PAPI placeholders inside of the countdown placeholder to done what you want.

You can download the new version by running the following commands:
```
/papi ecloud refresh
/papi ecloud diwnload server
/papi reload
```

**Comment by Thomoski** [comment]
Is there any documentation for how to use this addition? Release notes only mention the inclusion of the feature, not how to pass the %server_time% placeholder in the %server_countdown% placeholder

**Comment by UPSOKen** [comment]
> Is there any documentation for how to use this addition? Release notes only mention the inclusion of the feature, not how to pass the %server_time% placeholder in the %server_countdown% placeholder

Did this ever get documentation, because I still can't figure out how to do it correctly.

**Comment by SenorFlamingo** [comment]
If anyone is ever curious about this, you need to have a date set on top of the time you want it to count down to. The following will work if you want to have a countdown to 23:59:59:
`%server_countdown_dd.MM.yyyy-HH:mm:ss_{server_time_dd.MM.yyyy}-23:59:59%`
