### ISSUE TITLE
Some placeholders are broken with v2.7.1 update

### ISSUE THREAD

**Issue by kribjo** [PlaceholderAPI/Server-Expansion#57]
It seems v2.7.1 introduced some issues on Paper 1.20.4.
With v2.7.1 some placeholders are not parseable and instead spout warnings. Going back to 2.6.2 fixes the issues.

See this detailed report post at the Spigot PlaceholderAPI discussion:
https://www.spigotmc.org/threads/placeholderapi.61918/page-154#post-4727584

**Comment by SlimeDog** [comment]
Same issue on Paper 1.20.6 with PlaceholderAPI 2.11.6-DEV-193 and PAPI-Expansion-Server 2.7.1.

**Comment by SlimeDog** [comment]
Seems to be fixed with v2.7.2

**Comment by kribjo** [comment]
Seems fixed with 2.7.2 here too.

**Comment by iGabyTM** [comment]
Thank you for the confirmation
