### ISSUE TITLE
server_version_full & server_build return commit id rather than build id

### ISSUE THREAD

**Issue by SlimeDog** [PlaceholderAPI/Server-Expansion#59]
Starting with Paper 1.20.6-98 (and probably before), the version string includes the commit id
```
> version
[18:20:28 INFO]: This server is running Paper version 1.20.6-98-master@dff591d (2024-05-25T22:09:54Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
```
and
```
> papi parse --null %server_version_full%
[18:21:30 INFO]: 1.20.6-dff591d
```
instead of
```
> papi parse --null %server_version_full%
[18:21:30 INFO]: 1.20.6-98
```
as was returned in previous Paper versions.

**Comment by iGabyTM** [comment]
Can you please refresh my memory, why are these placeholders relevant to you? I fail to see an usage tbh.

**Comment by SlimeDog** [comment]
Use case: AdvancedServerList and ServerListPlus display server version in the multiplayer client screen.

**Comment by iGabyTM** [comment]
I don't understand

**Comment by SlimeDog** [comment]
Build [#60](https://github.com/PlaceholderAPI/Server-Expansion/pull/60) fixes it. Verified on Paper 1.21-37 and 1.20.6-147. Thanks.

**Comment by mart-r** [comment]
> I don't understand

I think the point is that for someone looking at the version string, a commit hash doesn't provide sequential information. You cannot tell which build is newer by just comparing two hashes. The user would need to go out of their way to look up the hash and its ordering in the sequence of builds.

**Comment by iGabyTM** [comment]
No, I mean still don't understand the need for such placeholders. @SlimeDog could you please try and explain the use case?

**Comment by SlimeDog** [comment]
![Screenshot 2024-06-24 at 15 28 51](https://github.com/PlaceholderAPI/Server-Expansion/assets/17748923/7c6ab77e-93ab-4733-885e-8c803e4b7699)

**Comment by SlimeDog** [comment]
To jog your memory, this was explicitly requested (by me) and implemented a few years ago. See https://github.com/PlaceholderAPI/Server-Expansion/issues/29.

**Comment by darbyjack** [comment]
That's a niche use-case I would have never thought of. Pretty cool!

**Comment by Andre601** [comment]
> To jog your memory, this was explicitly requested (by me) and implemented a few years ago. See https://github.com/PlaceholderAPI/Server-Expansion/issues/29.

Welp... this aged poorly...
![Screenshot_20240625-111549_GitHub.jpg](https://github.com/PlaceholderAPI/Server-Expansion/assets/11576465/2cee4205-0598-494c-933c-3557c079412b)
![SmartSelect_20240625-111611_GitHub.jpg](https://github.com/PlaceholderAPI/Server-Expansion/assets/11576465/d908531d-67e3-45fc-9efe-f12d84dbc4b0)

**Comment by SlimeDog** [comment]
My comment was meant as sarcasm, so it aged as expected.

**Comment by SlimeDog** [comment]
My comment was intended as sarcasm, so it aged as expected. Paper: move fast and break things.
