### ISSUE TITLE
placeholders dont work

### ISSUE THREAD

**Issue by lolw0tm8** [PlaceholderAPI/Server-Expansion#8]
### Issue
> What is the issue? Describe it like you would tell a friend.

Server placeholders don't work

### Expected behaviour
> What should PlaceholderAPI do?

%server_tps% is showing like this <- and not as number

### Actual behaviour
> What does PlaceholderAPI actually do?

nothing

### How to reproduce
> What steps did you made, to get this bug?

1. get placeholderapi
2. get tablist plugin
3. put any placeholder in it
4. see error

![2019-08-26_12 51 02](https://user-images.githubusercontent.com/53062952/63685799-92cd6400-c800-11e9-89a1-94ff88762bc2.png)

**Comment by aBo0oDyy** [comment]
Hey there,

Does that plugin supports PlaceholderAPI?
Did you download server expansion using these commands ?
```
/papi ecloud download Server
/papi reload
```

Are the placeholders working using papi parse commnd? `/papi parse me %server_ram_used%`?

And next time, open the issue in the correct place please.

**Comment by lolw0tm8** [comment]
did the command and it works now but the tps is tripled

**Comment by aBo0oDyy** [comment]
Well if it worked using the parse commnd, then your issue with that plugin, you'll have to contact the author of it.

What do you mean tripled? There's more than one TPS placeholder, you can find them all [here](https://helpch.at/placeholders#server). Use the one you like.

**Comment by lolw0tm8** [comment]
![2019-08-26_13 09 50](https://user-images.githubusercontent.com/53062952/63686768-07a19d80-c803-11e9-9459-368df21289d3.png)

**Comment by aBo0oDyy** [comment]
As i said,
> There's more than one TPS placeholder, you can find them all here. Use the one you like.
